export const ADDMOVIEFAVORITE = "ADD_MOVIE_FAVORITE";
export const GETMOVIES = "GET_MOVIES";
export const GETMOVIEDETAIL = "GET_MOVIE_DETAIL";
export const REMOVEMOVIEFAVORITE = "REMOVE_MOVIE_FAVORITE";

 
